/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellCalendarRouteImport } from './routes/_shell/calendar'
import { Route as ShellChatRouteImport } from './routes/_shell/chat'
import { Route as ShellClientsRouteImport } from './routes/_shell/clients'
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents'
import { Route as ShellReportsRouteImport } from './routes/_shell/reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminApprovalsRouteImport } from './routes/_admin/admin.approvals'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin.audit-logs'
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin/admin.employees'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as ShellCasesIndexRouteImport } from './routes/_shell/cases.index'
import { Route as ShellCasesCaseIdRouteImport } from './routes/_shell/cases.$caseId'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarRoute = ShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminApprovalsRoute = AdminAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ShellCasesIndexRoute = ShellCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCasesCaseIdRoute = ShellCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof ShellCalendarRoute
  '/chat': typeof ShellChatRoute
  '/clients': typeof ShellClientsRoute
  '/documents': typeof ShellDocumentsRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/tasks': typeof ShellTasksRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/cases/': typeof ShellCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof ShellCalendarRoute
  '/chat': typeof ShellChatRoute
  '/clients': typeof ShellClientsRoute
  '/documents': typeof ShellDocumentsRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/tasks': typeof ShellTasksRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cases': typeof ShellCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/calendar': typeof ShellCalendarRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/_admin/admin/approvals': typeof AdminAdminApprovalsRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/employees': typeof AdminAdminEmployeesRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_shell/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_shell/cases/': typeof ShellCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/documents'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/employees'
    | '/admin/settings'
    | '/cases/$caseId'
    | '/admin/'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/documents'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/employees'
    | '/admin/settings'
    | '/cases/$caseId'
    | '/admin'
    | '/cases'
  id:
    | '__root__'
    | '/_admin'
    | '/_shell'
    | '/login'
    | '/_shell/calendar'
    | '/_shell/chat'
    | '/_shell/clients'
    | '/_shell/documents'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/tasks'
    | '/_shell/'
    | '/_admin/admin/approvals'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/employees'
    | '/_admin/admin/settings'
    | '/_shell/cases/$caseId'
    | '/_admin/admin/'
    | '/_shell/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar': {
      id: '/_shell/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/approvals': {
      id: '/_admin/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminAdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/employees': {
      id: '/_admin/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shell/cases/': {
      id: '/_shell/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof ShellCasesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cases/$caseId': {
      id: '/_shell/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof ShellCasesCaseIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminApprovalsRoute: typeof AdminAdminApprovalsRoute
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminApprovalsRoute: AdminAdminApprovalsRoute,
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShellRouteChildren {
  ShellCalendarRoute: typeof ShellCalendarRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellClientsRoute: typeof ShellClientsRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCasesCaseIdRoute: typeof ShellCasesCaseIdRoute
  ShellCasesIndexRoute: typeof ShellCasesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCalendarRoute: ShellCalendarRoute,
  ShellChatRoute: ShellChatRoute,
  ShellClientsRoute: ShellClientsRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCasesCaseIdRoute: ShellCasesCaseIdRoute,
  ShellCasesIndexRoute: ShellCasesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
