/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellApprovalsRouteImport } from './routes/_shell/approvals'
import { Route as ShellAuditLogsRouteImport } from './routes/_shell/audit-logs'
import { Route as ShellCalendarRouteImport } from './routes/_shell/calendar'
import { Route as ShellChatRouteImport } from './routes/_shell/chat'
import { Route as ShellClientsRouteImport } from './routes/_shell/clients'
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents'
import { Route as ShellEmployeesRouteImport } from './routes/_shell/employees'
import { Route as ShellReportsRouteImport } from './routes/_shell/reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as ShellCasesIndexRouteImport } from './routes/_shell/cases.index'
import { Route as ShellCasesCaseIdRouteImport } from './routes/_shell/cases.$caseId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApprovalsRoute = ShellApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditLogsRoute = ShellAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarRoute = ShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmployeesRoute = ShellEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCasesIndexRoute = ShellCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCasesCaseIdRoute = ShellCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof ShellApprovalsRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/calendar': typeof ShellCalendarRoute
  '/chat': typeof ShellChatRoute
  '/clients': typeof ShellClientsRoute
  '/documents': typeof ShellDocumentsRoute
  '/employees': typeof ShellEmployeesRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/tasks': typeof ShellTasksRoute
  '/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/cases/': typeof ShellCasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof ShellApprovalsRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/calendar': typeof ShellCalendarRoute
  '/chat': typeof ShellChatRoute
  '/clients': typeof ShellClientsRoute
  '/documents': typeof ShellDocumentsRoute
  '/employees': typeof ShellEmployeesRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/tasks': typeof ShellTasksRoute
  '/': typeof ShellIndexRoute
  '/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/cases': typeof ShellCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/approvals': typeof ShellApprovalsRoute
  '/_shell/audit-logs': typeof ShellAuditLogsRoute
  '/_shell/calendar': typeof ShellCalendarRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/employees': typeof ShellEmployeesRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/cases/$caseId': typeof ShellCasesCaseIdRoute
  '/_shell/cases/': typeof ShellCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/audit-logs'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/documents'
    | '/employees'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/cases/$caseId'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/audit-logs'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/documents'
    | '/employees'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/'
    | '/cases/$caseId'
    | '/cases'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/approvals'
    | '/_shell/audit-logs'
    | '/_shell/calendar'
    | '/_shell/chat'
    | '/_shell/clients'
    | '/_shell/documents'
    | '/_shell/employees'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/tasks'
    | '/_shell/'
    | '/_shell/cases/$caseId'
    | '/_shell/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/approvals': {
      id: '/_shell/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ShellApprovalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit-logs': {
      id: '/_shell/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof ShellAuditLogsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar': {
      id: '/_shell/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/employees': {
      id: '/_shell/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ShellEmployeesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cases/': {
      id: '/_shell/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof ShellCasesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cases/$caseId': {
      id: '/_shell/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof ShellCasesCaseIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellApprovalsRoute: typeof ShellApprovalsRoute
  ShellAuditLogsRoute: typeof ShellAuditLogsRoute
  ShellCalendarRoute: typeof ShellCalendarRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellClientsRoute: typeof ShellClientsRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellEmployeesRoute: typeof ShellEmployeesRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCasesCaseIdRoute: typeof ShellCasesCaseIdRoute
  ShellCasesIndexRoute: typeof ShellCasesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellApprovalsRoute: ShellApprovalsRoute,
  ShellAuditLogsRoute: ShellAuditLogsRoute,
  ShellCalendarRoute: ShellCalendarRoute,
  ShellChatRoute: ShellChatRoute,
  ShellClientsRoute: ShellClientsRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellEmployeesRoute: ShellEmployeesRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCasesCaseIdRoute: ShellCasesCaseIdRoute,
  ShellCasesIndexRoute: ShellCasesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
